# makecvx.h
# this file goes in cgs

# -----------------------------------------------------------------------------
# directories for installation of generated files and executables
#
# -- the DIRS below must have a trailing / in their names --
# LIBDIR - dir for local libraries generated by cgs (recommend cgs/lib)
# INCDIR - dir for local include files used by cgs  (recommend cgs/include)
# EXEDIR - location for executable GENPLOT file
# DRVDIR - location for all run-time genplot files   (recommend cgs/bin)
# -- the DIRS below must NOT have a trailing / in their names --
# XINCDIR       - location of X-windows include files for x-term models
# INSTALLEXEDIR - directory for the one executable genplot to be installed
# INSTALLLIBDIR - directory for run support routines (install only)
# CONFIGLIBDIR  - normally identical to INSTALLLIBDIR unless you are running
#                 AFS.  Path CONFIGLIBDIR is built into program as path for
#                 finding files.  Install puts them in INSTALLLIBDIR.
# -----------------------------------------------------------------------------
MYROOT  = /home/cgs/cgs/
LIBDIR  = $(MYROOT)lib/
INCDIR  = $(MYROOT)include/
EXEDIR  = $(MYROOT)bin/
DRVDIR  = $(MYROOT)bin/
XINCDIR = /usr/include/X11
INSTALLEXEDIR = /usr/local/tware/
INSTALLLIBDIR = /usr/local/tware/OS2/
CONFIGLIBDIR  = /usr/local/tware/OS2/

# -----------------------------------------------------------------------------
# Default paths coded into program for finding TFM, fonts, etc files.  For
# MSDOS, use internal equivalence of / and \ so no problem (these are C
# strings, so if in MSDOS, use the \\ metachar)
#
# The CONFIGPATH will be used to search for character set stroke data
# (hdata.chr), initialization files (genplot.ini), help files (genplot.hlc),
# and run-time executables (drivers and X-term slave processes).  Should
# include $(DRVDIR) somewhere, or moves files from $(DRVDIR) to default path.
#
# The RUMPCONFIGPATH is the corresponding path for RUMP data files, such as
# atomic information, stopping powers.  It may be ignored if RUMP is not
# being installed.
# -----------------------------------------------------------------------------
CONFIGPATH = .:$(CONFIGLIBDIR)local:$(CONFIGLIBDIR)
RUMPCONFIGPATH = .:$(CONFIGLIBDIR)local:$(CONFIGLIBDIR)rump:$(CONFIGLIBDIR)

# ----------------------------------------------------------------------------
# Modify/control compilation parameters.  Change of these macros requires
# that all code be recompiled!  Make sure to do a clean first.
#
#     -DREAL_IS_DOUBLE  -- Causes internal real variable to be double instead
#                          of default float.  Data files remain float for
#                          compatibility.
#     -DTMPREAL_IS_LONG -- Causes temporary internal variables to be promoted
#                          to long double.  Since this is not ANSI compliant,
#                          no guarentees are given as to working status.
# ----------------------------------------------------------------------------
GPTOPTIONS = 

# ----------------------------------------------------------------------------
# Macros for the compiler, library manager, linker.  Options later.
#     CC         -- ANSI/POSIX compliant C compiler
#     ECC        -- extended ANSI/POSIX compiler (must handle POPEN/PCLOSE)
#     XCC        -- X-window ANSI/POSIX compiler (for x-term applications)
#     MKDIR      -- make subdirectory (add -p option if available)
#     INSTALLEXE -- install executable in local bins with proper chmod
#     INSTALLLIB -- install support files in local lib dir with proper chmod
# ----------------------------------------------------------------------------
CC     = cc
ECC    = cc
XCC    = cc
MKDIR  = mkdir
LIBMGR = ar rc
INSTALLEXE = install -o root -g staff -m 755 -c -s
INSTALLLIB = install -o root -g staff -m 644 -c

# ---------------------------------------------------------------------------
# Specify operating system type.  Limited set currently recognized.
#
#    OS2   - IBM Operating System 2 (OS/2 2.x)
#    NT    - Windows NT/95 Operating System
#    LINUX - Linux UNIX variant
#    UNIX  - All other UNIX variants
# ---------------------------------------------------------------------------
OSTYPE = UNIX

# ---------------------------------------------------------------------------
# Specify machine architecture.  Choices limited.  Used to set big/little
# endien handling, and may be combined with compiler for optional
# compilations.  By convention, these are case sensitive and normally lower.
#
#    Symbol             Architecture                   Big/Little Endian
#    -------            --------------                 -----------------
#    i386               Intel 386 architecture         little
#    i486               Intel 486 architecture         little
#    DECalpha           Digital Alpha-AXP              little
#    vax                Vax architecture               little
#    sgi                Silicon Graphics               (unknown!!!)
#    RISC6000           IBM RS6000 architecture        big
#    convex             Convex C210 architecture       big
#    sun                Sun architecture               big
#    sparc              sun sparc architecture         big
#    mc68000            Motorola 68000 architecture    big
#    sun386             don't know                     little
#    ns32000            don't know                     little
#    sel                don't know                     big
#    pyr                don't know                     big
#    is68k              don't know                     big
#    tahoe              don't know                     big
#    aiws               don't know                     big
#    BIT_ZERO_ON_RIGHT  generic                        little
#    BIT_ZERO_ON_LEFT   generic                        big
# ---------------------------------------------------------------------------
ARCHITECTURE = convex

# ---------------------------------------------------------------------------
# Specify compiler.
#
#    CSET2     - IBM CSET/2 C compiler
#    MSC60     - Microsoft C6.0 compiler
#    AIX_C     - IBM native AIX C compiler
#    SGI_C     - SGI native C compiler
#    GNU_C     - GNU C compiler (look for GNU_EXTENSIONS if early version)
#    CONVEX_C  - Convex native C compiler
#    OSF1_C    - Open Software Foundation C compiler on DEC Alpha.
# ---------------------------------------------------------------------------
COMPILER = CONVEX_C

# ----------------------------------------------------------------------------
# Turn on to enable debugging code in source, define DBG as -DDEBUG and set
# DBGOPTS with appropriate additional compile options (will be added to GOPTS)
# Also, you might want to consider disabling all optimizations for debugging.
# ----------------------------------------------------------------------------
# DBG = -DDEBUG
# DBGOPTS = -g

# ---------------------------------------------------------------------------
# Common and specific compiler options (see also SYSOPT below)
#   GOPTS - General options applied to all CC, ECC and XCC compiles
#   CCOPT - Additional options applied to  CC compiles only
#   ECOPT - Additional options applied to ECC compiles only
#   XCOPT - Additional options applied to XCC compiles only
#
# For GNU_C:
#   GOPTS = $(DBGOPTS) -ansi -Wall -O2
#   CCOPT =
#   ECOPT = -U__STRICT_ANSI__
#   XCOPT =
#   (for debugging, add at least "-Wshadow -Wcast-align -Wmissing-prototypes"
#    and possibly "-Wconversion and -Wstrict_prototypes")
#
# For CONVEX_C:
#   GOPTS = $(DBGOPTS) \
#           -d arg_ptr_qual=e -d arg_ptr_ref=e -d assign_in_condition=w \
#           -d const_not_init=w -d division_by_zero=e \
#           -d escape_range_sequence=e -d function_parameter=w \
#           -d hides_outer=w -d implicit_decl=w -d negative_to_uns=w \
#           -d no_arg_type=e -d no_external_declaration=w \
#           -d non_int_bit_field=w -d nothing_declared=w \
#           -d null_effect_expression=w -d pointer_alignment_efficiency=w \
#           -d strict_syntax=e
#   CCOPT = -std
#   ECOPT = 
#   XCOPT =
#
# For AIX_C: (optimize on)
#   GOPTS = -O $(DBGOPTS)
#   CCOPT = 
#   ECOPT = 
#   XCOPT =
#
# For SGI_C:
#   GOPTS = -ansiposix $(DBGOPTS)
#   CCOPT = 
#   ECOPT = 
#   XCOPT =
#
# For OSF1_C:
#   GOPTS = -std1 -O2 $(DBGOPTS)
#   CCOPT = 
#   ECOPT = 
#   XCOPT =
# ---------------------------------------------------------------------------
GOPTS = $(DBGOPTS) \
        -d arg_ptr_qual=e -d arg_ptr_ref=e -d assign_in_condition=w \
        -d const_not_init=w -d division_by_zero=e \
        -d escape_range_sequence=e -d function_parameter=w \
        -d hides_outer=w -d implicit_decl=w -d negative_to_uns=w \
        -d no_arg_type=e -d no_external_declaration=w \
        -d non_int_bit_field=w -d nothing_declared=w \
        -d null_effect_expression=w -d pointer_alignment_efficiency=w \
        -d strict_syntax=e
CCOPT = -std
ECOPT = 
XCOPT =

# ---------------------------------------------------------------------------
# System dependent options (beyond compiler options)
#
#    Ultrix:            SYSOPT = -D__mips -D__LANGUAGE_C -D__POSIX
#    Old gnu, maybe:    SYSOPT = -DGNU_EXTENSIONS
#    RS6000:            SYSOPT = -U__STR__ -D_XOPEN_SOURCE
#    Convex:            SYSOPT =
#    DEC alpha:         SYSOPT =
#
#    For all, add -DUNIX_PATH_EXTENSIONS to allow files with ~tommy/...
# ---------------------------------------------------------------------------
SYSOPT = -DUNIX_PATH_EXTENSIONS

# ---------------------------------------------------------------------------
# Declare linking libraries.  Must define
#  SYSLIBS  -- general system libraries needed in link (usually -lm)
#  XSYSLIBS -- additional system libraries needed for X packages
# ---------------------------------------------------------------------------
SYSLIBS  = -lm
XSYSLIBS = -lXt -lX11

# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# ---------- %% Be very careful changing below here %% ----------------------
# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# Combine a bunch of #defines on command line into one "DEFS" variable
# ---------------------------------------------------------------------------
DEFS = $(DBG) \
       -D$(OSTYPE) -D$(ARCHITECTURE) -D$(COMPILER) \
       -DCONFIGPATH=\"$(CONFIGPATH)\" $(GPTOPTIONS)

# ----------------------------------------------------------------------------
# Combine all options for compilers.  Declares
#  $(CFLAGS) -- $(CC)  options, standard ANSI/POSIX compiler
#  $(EFLAGS) -- $(ECC) options, extended ANSI/POSIX compiler
#  $(XFLAGS) -- $(XCC) options, X-window ANSI/POSIX compiler
#  $(LIBS)   -- local libs to be linked for GENPLOT
#
# See final implicit rules.  There may be explicit $(ECC) $(EFLAGS) and 
# $(XCC) $(XFLAGS) in local makefiles.  Anything more in default rules than
#    .c.o: $(CC) $(CFLAGS) -c $< 
# will require twiddling of subdirectory makefiles.
# ----------------------------------------------------------------------------
CL=
CFLAGS = $(GOPTS) $(CCOPT) -I$(INCDIR) $(SYSOPT) $(DEFS)
EFLAGS = $(GOPTS) $(ECOPT) -I$(INCDIR) $(SYSOPT) $(DEFS)
XFLAGS = $(GOPTS) $(XCOPT) -I$(INCDIR) -I$(XINCDIR) $(SYSOPT) $(DEFS)

LIBS   = $(LIBDIR)tplot.a $(LIBDIR)lexp.a $(LIBDIR)posix.a

# --------------------------------------------------------------------------
# -- Set local inference rules basically turning everything off!
# --------------------------------------------------------------------------
# Inference rules
.SUFFIXES:
.SUFFIXES: .o .c

# Compile command for default objects
.c.o:
	$(CC) $(CFLAGS) -c $<
