/*  ------------------------------------------------------------------------- */
/*  ---------                                              ------------------ */
/*  --------- COPYRIGHT 1989 (c) Computer Graphics Service ------------------ */
/*  ---------                                              ------------------ */
/*  ---------    The source code to RUMP may be freely     ------------------ */
/*  ---------  modified as long as this copyright notice   ------------------ */
/*  ---------          is included and unchanged.          ------------------ */
/*  ------------------------------------------------------------------------- */

#ifndef MINIMAL_RUMP_INCLUDE			/* Normal situation, except main */

/* Support routines common with Genplot: */
#include "mytypes.h"
#include "extends.h"
#include "lexp.h"

/* RUMP Specific stuff: */
#include "spectrum.h"
#include "rumpdata.h"
#include "rumpproto.h"
#include "rkeys.h"

#endif

/* -- Following defined for minimal rump.h loading - needed in main.c -- */
int Rump(void);										/* Main program	*/
char *RbsGetSearchPath(void);						/* Path lookup		*/

/* serial.c relevent variables */
#ifdef XRUMPHLP_C_SOURCE
	EXPORT const char  RumpRevisionLevel[];
	EXPORT const char  RumpLinkDate[];
	EXPORT const REAL  RumpVersionNumber;
#else
	IMPORT const char  RumpRevisionLevel[];
	IMPORT const char  RumpLinkDate[];
	IMPORT const REAL  RumpVersionNumber;
#endif
IMPORT const char  RumpRevisionDate[];				/* From revision.h autogenerated file */
EXTERN const char *RumpDefaultConfigPath;

/* rump.c relevent variables */
#ifdef CONFIG_C_SOURCE
	EXPORT char RbsAtomicDataFile[PATH_MAX];		/* Atomic info data file	*/
#else
	IMPORT char RbsAtomicDataFile[PATH_MAX];		/* Atomic info data file	*/
#endif
EXTERN char *RbsConfigPath;							/* Default search path		*/
